version: '3'
services:
  api:
    build: api
    depends_on:
      - redis
      - postgres_db
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres_db
    command: npm run start
  worker:
    build: worker
    depends_on:
      - redis
      - postgres_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres_db
    command: npm run start
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres_db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
